// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/lib/mcp/tools/list-clients.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(auth2) {
  const token = auth2.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-clients.ts
var list_clients_default = defineTool({
  name: "list_clients",
  title: "List clients",
  description: "List clients in the signed-in user's organization, newest first.",
  inputSchema: {
    search: z.string().trim().min(1).nullable().describe("Optional name or company text to filter by."),
    limit: z.number().int().min(1).max(100).nullable().describe("Maximum number of clients to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("clients").select("id, name, company, email, phone, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (search) query = query.or(`name.ilike.%${search}%,company.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) throw new ToolError(error.message);
    const clients = (data ?? []).map((c) => ({
      id: c.id,
      name: c.name,
      company: c.company ?? null,
      email: c.email ?? null,
      phone: c.phone ?? null,
      created_at: c.created_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(clients, null, 2) }],
      structuredContent: { clients }
    };
  }
});

// src/lib/mcp/tools/create-client.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z2 } from "npm:zod@^3.25.76";
var create_client_default = defineTool2({
  name: "create_client",
  title: "Create client",
  description: "Create a new client record in the signed-in user's organization.",
  inputSchema: {
    name: z2.string().trim().min(1).describe("Client contact name."),
    company: z2.string().trim().min(1).nullable().describe("Company name, if any."),
    email: z2.string().trim().email().nullable().describe("Contact email, if any."),
    phone: z2.string().trim().min(1).nullable().describe("Contact phone, if any."),
    notes: z2.string().trim().min(1).nullable().describe("Internal notes, if any.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, company, email, phone, notes }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: profile, error: profileError } = await supabase.from("profiles").select("org_id").eq("user_id", userId).single();
    if (profileError) throw new ToolError2(profileError.message);
    const { data, error } = await supabase.from("clients").insert({
      name,
      company,
      email,
      phone,
      notes,
      created_by: userId,
      org_id: profile?.org_id ?? null
    }).select("id, name, company, email, phone, created_at").single();
    if (error) throw new ToolError2(error.message);
    const client = {
      id: data.id,
      name: data.name,
      company: data.company ?? null,
      email: data.email ?? null,
      phone: data.phone ?? null,
      created_at: data.created_at
    };
    return {
      content: [{ type: "text", text: `Created client "${client.name}" (${client.id}).` }],
      structuredContent: { client }
    };
  }
});

// src/lib/mcp/tools/list-proposals.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_proposals_default = defineTool3({
  name: "list_proposals",
  title: "List proposals",
  description: "List proposals (quotes) visible to the signed-in user, newest first, optionally filtered by status.",
  inputSchema: {
    status: z3.enum(["draft", "sent", "viewed", "accepted", "rejected", "expired"]).nullable().describe("Optional status filter."),
    limit: z3.number().int().min(1).max(100).nullable().describe("Maximum number of proposals to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("proposals").select("id, title, status, subtotal, total, tax_rate, discount_total, valid_until, created_at, updated_at, clients(name)").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) throw new ToolError3(error.message);
    const proposals = (data ?? []).map((p) => ({
      id: p.id,
      title: p.title,
      status: p.status,
      client_name: (() => {
        const c = p.clients;
        const one = Array.isArray(c) ? c[0] : c;
        return one?.name ?? null;
      })(),
      subtotal: p.subtotal ?? null,
      total: p.total ?? null,
      tax_rate: p.tax_rate ?? null,
      discount_total: p.discount_total ?? null,
      valid_until: p.valid_until ?? null,
      created_at: p.created_at,
      updated_at: p.updated_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(proposals, null, 2) }],
      structuredContent: { proposals }
    };
  }
});

// src/lib/mcp/tools/get-proposal.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_proposal_default = defineTool4({
  name: "get_proposal",
  title: "Get proposal",
  description: "Get one proposal with its line items, by proposal id.",
  inputSchema: {
    proposal_id: z4.string().uuid().describe("The proposal id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ proposal_id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("proposals").select("id, title, status, notes, subtotal, total, tax_rate, discount_total, valid_until, created_at, updated_at, clients(name, company, email)").eq("id", proposal_id).maybeSingle();
    if (error) throw new ToolError4(error.message);
    if (!data) throw new ToolError4("Proposal not found or not accessible");
    const { data: items, error: itemsError } = await supabase.from("line_items").select("id, description, quantity, rate, discount, amount, sort_order").eq("proposal_id", proposal_id).order("sort_order", { ascending: true });
    if (itemsError) throw new ToolError4(itemsError.message);
    const rawClient = data.clients;
    const client = Array.isArray(rawClient) ? rawClient[0] ?? null : rawClient;
    const proposal = {
      id: data.id,
      title: data.title,
      status: data.status,
      notes: data.notes ?? null,
      subtotal: data.subtotal ?? null,
      total: data.total ?? null,
      tax_rate: data.tax_rate ?? null,
      discount_total: data.discount_total ?? null,
      valid_until: data.valid_until ?? null,
      created_at: data.created_at,
      updated_at: data.updated_at,
      client: client ? { name: client.name, company: client.company ?? null, email: client.email ?? null } : null,
      line_items: (items ?? []).map((i) => ({
        id: i.id,
        description: i.description,
        quantity: i.quantity,
        rate: i.rate,
        discount: i.discount ?? null,
        amount: i.amount ?? null,
        sort_order: i.sort_order
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(proposal, null, 2) }],
      structuredContent: { proposal }
    };
  }
});

// src/lib/mcp/tools/list-templates.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_templates_default = defineTool5({
  name: "list_templates",
  title: "List templates",
  description: "List proposal templates available to the signed-in user.",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).nullable().describe("Maximum number of templates to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError5("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("templates").select("id, name, description, category, is_default, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) throw new ToolError5(error.message);
    const templates = (data ?? []).map((t) => ({
      id: t.id,
      name: t.name,
      description: t.description ?? null,
      category: t.category,
      is_default: t.is_default,
      created_at: t.created_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(templates, null, 2) }],
      structuredContent: { templates }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sxpdamzprqfnwlwraapy";
var mcp_default = defineMcp({
  name: "fafo-smsh-ttc-rs-of-quote-generator",
  title: "FAFO-SMSH/TTC/RS of Quote Generator",
  version: "0.1.0",
  instructions: "Tools for the quote generator app. Use `list_proposals` and `get_proposal` to read quotes and their line items, `list_clients` and `create_client` for clients, and `list_templates` for proposal templates. All tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_proposals_default, get_proposal_default, list_clients_default, create_client_default, list_templates_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
